//Source:  https://en.wikipedia.org/wiki/ISO_4217 (2022/08/08)
const currencies = {
  AED: { code: "AED", name: "United Arab Emirates dirham", locations: ["United Arab Emirates"] },
  AFN: { code: "AFN", name: "Afghan afghani", locations: ["Afghanistan"] },
  ALL: { code: "ALL", name: "Albanian lek", locations: ["Albania"] },
  AMD: { code: "AMD", name: "Armenian dram", locations: ["Armenia"] },
  ANG: { code: "ANG", name: "Netherlands Antillean guilder", locations: ["Curaçao (CW)", "Sint Maarten (SX)"] },
  AOA: { code: "AOA", name: "Angolan kwanza", locations: ["Angola"] },
  ARS: { code: "ARS", name: "Argentine peso", locations: ["Argentina"] },
  AUD: {
    code: "AUD",
    name: "Australian dollar",
    locations: [
      "Australia",
      "Christmas Island (CX)",
      "Cocos (Keeling) Islands (CC)",
      "Heard Island and McDonald Islands (HM)",
      "Kiribati (KI)",
      "Nauru (NR)",
      "Norfolk Island (NF)",
      "Tuvalu (TV)",
    ],
  },
  AWG: { code: "AWG", name: "Aruban florin", locations: ["Aruba"] },
  AZN: { code: "AZN", name: "Azerbaijani manat", locations: ["Azerbaijan"] },
  BAM: { code: "BAM", name: "Bosnia and Herzegovina convertible mark", locations: ["Bosnia and Herzegovina"] },
  BBD: { code: "BBD", name: "Barbados dollar", locations: ["Barbados"] },
  BDT: { code: "BDT", name: "Bangladeshi taka", locations: ["Bangladesh"] },
  BGN: { code: "BGN", name: "Bulgarian lev", locations: ["Bulgaria"] },
  BHD: { code: "BHD", name: "Bahraini dinar", locations: ["Bahrain"] },
  BIF: { code: "BIF", name: "Burundian franc", locations: ["Burundi"] },
  BMD: { code: "BMD", name: "Bermudian dollar", locations: ["Bermuda"] },
  BND: { code: "BND", name: "Brunei dollar", locations: ["Brunei"] },
  BOB: { code: "BOB", name: "Boliviano", locations: ["Bolivia"] },
  BOV: { code: "BOV", name: "Bolivian Mvdol (funds code)", locations: ["Bolivia"] },
  BRL: { code: "BRL", name: "Brazilian real", locations: ["Brazil"] },
  BSD: { code: "BSD", name: "Bahamian dollar", locations: ["Bahamas"] },
  BTN: { code: "BTN", name: "Bhutanese ngultrum", locations: ["Bhutan"] },
  BWP: { code: "BWP", name: "Botswana pula", locations: ["Botswana"] },
  BYN: { code: "BYN", name: "Belarusian ruble", locations: ["Belarus"] },
  BZD: { code: "BZD", name: "Belize dollar", locations: ["Belize"] },
  CAD: { code: "CAD", name: "Canadian dollar", locations: ["Canada"] },
  CDF: { code: "CDF", name: "Congolese franc", locations: ["Democratic Republic of the Congo"] },
  CHE: { code: "CHE", name: "WIR euro (complementary currency)", locations: [" Switzerland"] },
  CHF: { code: "CHF", name: "Swiss franc", locations: [" Switzerland,  Liechtenstein (LI)"] },
  CHW: { code: "CHW", name: "WIR franc (complementary currency)", locations: [" Switzerland"] },
  CLF: { code: "CLF", name: "Unidad de Fomento (funds code)", locations: ["Chile"] },
  CLP: { code: "CLP", name: "Chilean peso", locations: ["Chile"] },
  COP: { code: "COP", name: "Colombian peso", locations: ["Colombia"] },
  COU: { code: "COU", name: "Unidad de Valor Real (UVR) (funds code)[9]", locations: ["Colombia"] },
  CRC: { code: "CRC", name: "Costa Rican colon", locations: ["Costa Rica"] },
  CUC: { code: "CUC", name: "Cuban convertible peso", locations: ["Cuba"] },
  CUP: { code: "CUP", name: "Cuban peso", locations: ["Cuba"] },
  CVE: { code: "CVE", name: "Cape Verdean escudo", locations: ["Cabo Verde"] },
  CZK: { code: "CZK", name: "Czech koruna", locations: ["Czechia[10]"] },
  DJF: { code: "DJF", name: "Djiboutian franc", locations: ["Djibouti"] },
  DKK: { code: "DKK", name: "Danish krone", locations: ["Denmark", "Faroe Islands (FO)", "Greenland (GL)"] },
  DOP: { code: "DOP", name: "Dominican peso", locations: ["Dominican Republic"] },
  DZD: { code: "DZD", name: "Algerian dinar", locations: ["Algeria"] },
  EGP: { code: "EGP", name: "Egyptian pound", locations: ["Egypt"] },
  ERN: { code: "ERN", name: "Eritrean nakfa", locations: ["Eritrea"] },
  ETB: { code: "ETB", name: "Ethiopian birr", locations: ["Ethiopia"] },
  EUR: {
    code: "EUR",
    name: "Euro",
    locations: [
      "Åland Islands (AX),  European Union (EU),  Andorra (AD),   Austria (AT),  Belgium (BE),  Cyprus (CY),  Estonia (EE),  Finland (FI),  France (FR),  French Southern and Antarctic Lands (TF),  Germany (DE),  Greece (GR),  Guadeloupe (GP),  Ireland (IE),  Italy (IT),  Latvia (LV),  Lithuania (LT),  Luxembourg (LU),  Malta (MT),  French Guiana (GF),  Martinique (MQ),  Mayotte (YT),  Monaco (MC),  Montenegro (ME),  Netherlands (NL),  Portugal (PT),  Réunion (RE),  Saint Barthélemy (BL),  Saint Martin (MF),  Saint Pierre and Miquelon (PM),  San Marino (SM),  Slovakia (SK),  Slovenia (SI),  Spain (ES),   Vatican City (VA)",
    ],
  },
  FJD: { code: "FJD", name: "Fiji dollar", locations: ["Fiji"] },
  FKP: { code: "FKP", name: "Falkland Islands pound", locations: ["Falkland Islands (pegged to GBP 1:1)"] },
  GBP: {
    code: "GBP",
    name: "Pound sterling",
    locations: [
      "United Kingdom",
      "Isle of Man (IM",
      "see Manx pound)",
      "Jersey (JE",
      "see Jersey pound)",
      "Guernsey (GG",
      "see Guernsey pound)",
      "Tristan da Cunha (SH-TA)",
    ],
  },
  GEL: { code: "GEL", name: "Georgian lari", locations: ["Georgia"] },
  GHS: { code: "GHS", name: "Ghanaian cedi", locations: ["Ghana"] },
  GIP: { code: "GIP", name: "Gibraltar pound", locations: ["Gibraltar (pegged to GBP 1:1)"] },
  GMD: { code: "GMD", name: "Gambian dalasi", locations: ["Gambia"] },
  GNF: { code: "GNF", name: "Guinean franc", locations: ["Guinea"] },
  GTQ: { code: "GTQ", name: "Guatemalan quetzal", locations: ["Guatemala"] },
  GYD: { code: "GYD", name: "Guyanese dollar", locations: ["Guyana"] },
  HKD: { code: "HKD", name: "Hong Kong dollar", locations: ["Hong Kong"] },
  HNL: { code: "HNL", name: "Honduran lempira", locations: ["Honduras"] },
  HRK: { code: "HRK", name: "Croatian kuna", locations: ["Croatia"] },
  HTG: { code: "HTG", name: "Haitian gourde", locations: ["Haiti"] },
  HUF: { code: "HUF", name: "Hungarian forint", locations: ["Hungary"] },
  IDR: { code: "IDR", name: "Indonesian rupiah", locations: ["Indonesia"] },
  ILS: { code: "ILS", name: "Israeli new shekel", locations: ["Israel"] },
  INR: { code: "INR", name: "Indian rupee", locations: ["India", "Bhutan"] },
  IQD: { code: "IQD", name: "Iraqi dinar", locations: ["Iraq"] },
  IRR: { code: "IRR", name: "Iranian rial", locations: ["Iran"] },
  ISK: { code: "ISK", name: "Icelandic króna (plural: krónur)", locations: ["Iceland"] },
  JMD: { code: "JMD", name: "Jamaican dollar", locations: ["Jamaica"] },
  JOD: { code: "JOD", name: "Jordanian dinar", locations: ["Jordan"] },
  JPY: { code: "JPY", name: "Japanese yen", locations: ["Japan"] },
  KES: { code: "KES", name: "Kenyan shilling", locations: ["Kenya"] },
  KGS: { code: "KGS", name: "Kyrgyzstani som", locations: ["Kyrgyzstan"] },
  KHR: { code: "KHR", name: "Cambodian riel", locations: ["Cambodia"] },
  KMF: { code: "KMF", name: "Comoro franc", locations: ["Comoros"] },
  KPW: { code: "KPW", name: "North Korean won", locations: ["North Korea"] },
  KRW: { code: "KRW", name: "South Korean won", locations: ["South Korea"] },
  KWD: { code: "KWD", name: "Kuwaiti dinar", locations: ["Kuwait"] },
  KYD: { code: "KYD", name: "Cayman Islands dollar", locations: ["Cayman Islands"] },
  KZT: { code: "KZT", name: "Kazakhstani tenge", locations: ["Kazakhstan"] },
  LAK: { code: "LAK", name: "Lao kip", locations: ["Laos"] },
  LBP: { code: "LBP", name: "Lebanese pound", locations: ["Lebanon"] },
  LKR: { code: "LKR", name: "Sri Lankan rupee", locations: ["Sri Lanka"] },
  LRD: { code: "LRD", name: "Liberian dollar", locations: ["Liberia"] },
  LSL: { code: "LSL", name: "Lesotho loti", locations: ["Lesotho"] },
  LYD: { code: "LYD", name: "Libyan dinar", locations: ["Libya"] },
  MAD: { code: "MAD", name: "Moroccan dirham", locations: ["Morocco", "Western Sahara"] },
  MDL: { code: "MDL", name: "Moldovan leu", locations: ["Moldova"] },
  MGA: { code: "MGA", name: "Malagasy ariary", locations: ["Madagascar"] },
  MKD: { code: "MKD", name: "Macedonian denar", locations: ["North Macedonia"] },
  MMK: { code: "MMK", name: "Myanmar kyat", locations: ["Myanmar"] },
  MNT: { code: "MNT", name: "Mongolian tögrög", locations: ["Mongolia"] },
  MOP: { code: "MOP", name: "Macanese pataca", locations: ["Macau"] },
  MRU: { code: "MRU", name: "Mauritanian ouguiya", locations: ["Mauritania"] },
  MUR: { code: "MUR", name: "Mauritian rupee", locations: ["Mauritius"] },
  MVR: { code: "MVR", name: "Maldivian rufiyaa", locations: ["Maldives"] },
  MWK: { code: "MWK", name: "Malawian kwacha", locations: ["Malawi"] },
  MXN: { code: "MXN", name: "Mexican peso", locations: ["Mexico"] },
  MXV: { code: "MXV", name: "Mexican Unidad de Inversion (UDI) (funds code)", locations: ["Mexico"] },
  MYR: { code: "MYR", name: "Malaysian ringgit", locations: ["Malaysia"] },
  MZN: { code: "MZN", name: "Mozambican metical", locations: ["Mozambique"] },
  NAD: { code: "NAD", name: "Namibian dollar", locations: ["Namibia (pegged to ZAR 1:1)"] },
  NGN: { code: "NGN", name: "Nigerian naira", locations: ["Nigeria"] },
  NIO: { code: "NIO", name: "Nicaraguan córdoba", locations: ["Nicaragua"] },
  NOK: {
    code: "NOK",
    name: "Norwegian krone",
    locations: ["Norway", "Svalbard and  Jan Mayen (SJ)", "Bouvet Island (BV)"],
  },
  NPR: { code: "NPR", name: "Nepalese rupee", locations: ["  Nepal"] },
  NZD: {
    code: "NZD",
    name: "New Zealand dollar",
    locations: [
      "New Zealand",
      "Cook Islands (CK)",
      "Niue (NU)",
      "Pitcairn Islands (PN; see also Pitcairn Islands dollar)",
      "Tokelau (TK)",
    ],
  },
  OMR: { code: "OMR", name: "Omani rial", locations: ["Oman"] },
  PAB: { code: "PAB", name: "Panamanian balboa", locations: ["Panama"] },
  PEN: { code: "PEN", name: "Peruvian sol", locations: ["Peru"] },
  PGK: { code: "PGK", name: "Papua New Guinean kina", locations: ["Papua New Guinea"] },
  PHP: { code: "PHP", name: "Philippine peso[13]", locations: ["Philippines"] },
  PKR: { code: "PKR", name: "Pakistani rupee", locations: ["Pakistan"] },
  PLN: { code: "PLN", name: "Polish złoty", locations: ["Poland"] },
  PYG: { code: "PYG", name: "Paraguayan guaraní", locations: ["Paraguay"] },
  QAR: { code: "QAR", name: "Qatari riyal", locations: ["Qatar"] },
  RON: { code: "RON", name: "Romanian leu", locations: ["Romania"] },
  RSD: { code: "RSD", name: "Serbian dinar", locations: ["Serbia"] },
  CNY: { code: "CNY", name: "Renminbi[14]", locations: ["China"] },
  RUB: { code: "RUB", name: "Russian ruble", locations: ["Russia"] },
  RWF: { code: "RWF", name: "Rwandan franc", locations: ["Rwanda"] },
  SAR: { code: "SAR", name: "Saudi riyal", locations: ["Saudi Arabia"] },
  SBD: { code: "SBD", name: "Solomon Islands dollar", locations: ["Solomon Islands"] },
  SCR: { code: "SCR", name: "Seychelles rupee", locations: ["Seychelles"] },
  SDG: { code: "SDG", name: "Sudanese pound", locations: ["Sudan"] },
  SEK: { code: "SEK", name: "Swedish krona (plural: kronor)", locations: ["Sweden"] },
  SGD: { code: "SGD", name: "Singapore dollar", locations: ["Singapore"] },
  SHP: { code: "SHP", name: "Saint Helena pound", locations: ["Saint Helena (SH-SH)", "Ascension Island (SH-AC)"] },
  SLL: { code: "SLL", name: "Sierra Leonean", locations: ["leone"] },
  SLE: { code: "SLE", name: "Sierra Leonean", locations: ["leone"] },
  SOS: { code: "SOS", name: "Somali shilling", locations: ["Somalia"] },
  SRD: { code: "SRD", name: "Surinamese dollar", locations: ["Suriname"] },
  SSP: { code: "SSP", name: "South Sudanese pound", locations: ["South Sudan"] },
  STN: { code: "STN", name: "São Tomé and Príncipe dobra", locations: ["São Tomé and Príncipe"] },
  SVC: { code: "SVC", name: "Salvadoran colón", locations: ["El Salvador"] },
  SYP: { code: "SYP", name: "Syrian pound", locations: ["Syria"] },
  SZL: { code: "SZL", name: "Swazi lilangeni", locations: ["Eswatini[13]"] },
  THB: { code: "THB", name: "Thai baht", locations: ["Thailand"] },
  TJS: { code: "TJS", name: "Tajikistani somoni", locations: ["Tajikistan"] },
  TMT: { code: "TMT", name: "Turkmenistan manat", locations: ["Turkmenistan"] },
  TND: { code: "TND", name: "Tunisian dinar", locations: ["Tunisia"] },
  TOP: { code: "TOP", name: "Tongan paʻanga", locations: ["Tonga"] },
  TRY: { code: "TRY", name: "Turkish lira", locations: ["Turkey"] },
  TTD: { code: "TTD", name: "Trinidad and Tobago dollar", locations: ["Trinidad and Tobago"] },
  TWD: { code: "TWD", name: "New Taiwan dollar", locations: ["Taiwan"] },
  TZS: { code: "TZS", name: "Tanzanian shilling", locations: ["Tanzania"] },
  UAH: { code: "UAH", name: "Ukrainian hryvnia", locations: ["Ukraine"] },
  UGX: { code: "UGX", name: "Ugandan shilling", locations: ["Uganda"] },
  USD: {
    code: "USD",
    name: "United States dollar",
    locations: [
      "United States",
      "American Samoa (AS)",
      "British Indian Ocean Territory (IO) (also uses GBP)",
      "British Virgin Islands (VG)",
      "Caribbean Netherlands (BQ – Bonaire",
      "Sint Eustatius and Saba)",
      "Ecuador (EC)",
      "El Salvador (SV)",
      "Guam (GU)",
      "Marshall Islands (MH)",
      "Federated States of Micronesia (FM)",
      "Northern Mariana Islands (MP)",
      "Palau (PW)",
      "Panama (PA) (as well as Panamanian Balboa)",
      "Puerto Rico (PR)",
      "Timor-Leste (TL)",
      "Turks and Caicos Islands (TC)",
      "U.S. Virgin Islands (VI)",
      "United States Minor Outlying Islands (UM)",
    ],
  },
  USN: { code: "USN", name: "United States dollar (next day) (funds code)", locations: ["United States"] },
  UYI: { code: "UYI", name: "Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)", locations: ["Uruguay"] },
  UYU: { code: "UYU", name: "Uruguayan peso", locations: ["Uruguay"] },
  UYW: { code: "UYW", name: "Unidad previsional[16]", locations: ["Uruguay"] },
  UZS: { code: "UZS", name: "Uzbekistan som", locations: ["Uzbekistan"] },
  VED: { code: "VED", name: "Venezuelan bolívar digital[17]", locations: ["Venezuela"] },
  VES: { code: "VES", name: "Venezuelan bolívar soberano[13]", locations: ["Venezuela"] },
  VND: { code: "VND", name: "Vietnamese đồng", locations: ["Vietnam"] },
  VUV: { code: "VUV", name: "Vanuatu vatu", locations: ["Vanuatu"] },
  WST: { code: "WST", name: "Samoan tala", locations: ["Samoa"] },
  XAF: {
    code: "XAF",
    name: "CFA franc BEAC",
    locations: [
      "Cameroon (CM)",
      "Central African Republic (CF)",
      "Republic of the Congo (CG)",
      "Chad (TD)",
      "Equatorial Guinea (GQ)",
      "Gabon (GA)",
    ],
  },
  XAG: { code: "XAG", name: "Silver (one troy ounce)", locations: [""] },
  XAU: { code: "XAU", name: "Gold (one troy ounce)", locations: [""] },
  XBA: { code: "XBA", name: "European Composite Unit (EURCO) (bond market unit)", locations: [""] },
  XBB: { code: "XBB", name: "European Monetary Unit (E.M.U.-6) (bond market unit)", locations: [""] },
  XBC: { code: "XBC", name: "European Unit of Account 9 (E.U.A.-9) (bond market unit)", locations: [""] },
  XBD: { code: "XBD", name: "European Unit of Account 17 (E.U.A.-17) (bond market unit)", locations: [""] },
  XCD: {
    code: "XCD",
    name: "East Caribbean dollar",
    locations: [
      "Anguilla (AI)",
      "Antigua and Barbuda (AG)",
      "Dominica (DM)",
      "Grenada (GD)",
      "Montserrat (MS)",
      "Saint Kitts and Nevis (KN)",
      "Saint Lucia (LC)",
      "Saint Vincent and the Grenadines (VC)",
    ],
  },
  XDR: { code: "XDR", name: "Special drawing rights", locations: ["International Monetary Fund"] },
  XOF: {
    code: "XOF",
    name: "CFA franc BCEAO",
    locations: [
      "Benin (BJ)",
      "Burkina Faso (BF)",
      "Côte d'Ivoire (CI)",
      "Guinea-Bissau (GW)",
      "Mali (ML)",
      "Niger (NE)",
      "Senegal (SN)",
      "Togo (TG)",
    ],
  },
  XPD: { code: "XPD", name: "Palladium (one troy ounce)", locations: [""] },
  XPF: {
    code: "XPF",
    name: "CFP franc (franc Pacifique)",
    locations: [
      "French territories of the Pacific Ocean:  French Polynesia (PF)",
      "New Caledonia (NC)",
      "Wallis and Futuna (WF)",
    ],
  },
  XPT: { code: "XPT", name: "Platinum (one troy ounce)", locations: [""] },
  XSU: { code: "XSU", name: "SUCRE", locations: ["Unified System for Regional Compensation (SUCRE)[18]"] },
  XTS: { code: "XTS", name: "Code reserved for testing", locations: [""] },
  XUA: { code: "XUA", name: "ADB Unit of Account", locations: ["African Development Bank[19]"] },
  XXX: { code: "XXX", name: "No currency", locations: [""] },
  YER: { code: "YER", name: "Yemeni rial", locations: ["Yemen"] },
  ZAR: { code: "ZAR", name: "South African rand", locations: ["Eswatini", "Lesotho", "Namibia", "South Africa"] },
  ZMW: { code: "ZMW", name: "Zambian kwacha", locations: ["Zambia"] },
  ZWL: { code: "ZWL", name: "Zimbabwean dollar", locations: ["Zimbabwe"] },
};
